/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/metaquast.py -o /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/job_working_directory/001/1008/dataset_1091_files -R /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/files/000/dataset_895.dat -G /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/files/000/dataset_903.dat /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/files/000/dataset_497.dat

Version 2.2, build 19.07.2013 21:21


System information:
  OS: Linux-2.6.18-371.el5-x86_64-with-redhat-5.10-Tikanga
  Python version: 2.7.0
  CPUs number: 64

Started: 2014-03-24 10:35:59

Logging to /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/job_working_directory/001/1008/dataset_1091_files/metaquast.log

References:
  /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/files/000/dataset_895.dat:
    dataset_895

    dataset_895

  All references combined in combined_reference.fasta

Contigs:
  /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/files/000/dataset_497.dat ==> dataset_497.dat

Starting quast.py for the combined reference...
(logging to /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/database/job_working_directory/001/1008/dataset_1091_files/combined_quast_output/quast.log)

list index out of range
Traceback (most recent call last):
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/metaquast.py", line 511, in <module>
    return_code = main(sys.argv[1:])
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/metaquast.py", line 468, in main
    output_dirpath=os.path.join(output_dirpath, 'combined_quast_output'))
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/metaquast.py", line 159, in _start_quast_main
    return quast.main(args)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/quast.py", line 653, in main
    ref_fpath, contigs_fpaths, qconfig.prokaryote, os.path.join(output_dirpath, 'contigs_reports'))
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/contigs_analyzer.py", line 1270, in do
    for id, fname in enumerate(contigs_fpaths))
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/site_packages/joblib/parallel.py", line 483, in __call__
    self.dispatch(function, args, kwargs)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/site_packages/joblib/parallel.py", line 306, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/site_packages/joblib/parallel.py", line 134, in __init__
    self.results = func(*args, **kwargs)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/contigs_analyzer.py", line 1219, in plantakolya_process
    cyclic, i, contigs_fpath, nucmer_fname, myenv, output_dirpath, ref_fpath)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/contigs_analyzer.py", line 205, in plantakolya
    coords_file.write(header[-2])
IndexError: list index out of range
